import localFont from "next/font/local";
import "./globals.css";
import MainNavigation from "@/components/layout/main-navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Nextjs demo project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add the link to the notifications.css */}
        <link rel="stylesheet" type="text/css" href="/path/to/notifications.css" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MainNavigation />
        {children}
      </body>
    </html>
  );
}
