import localFont from "next/font/local";
import "./globals.css";
import NavigationWrapper from "@/components/layout/NavigationWrapper";  // Import the new client-side wrapper component
import AuthProvider from "@/provider/AuthProvider";
import { authOptions } from '@/lib/authOptions'
import { getServerSession } from "next-auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Nextjs demo project",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)
  return (
    <AuthProvider session={session}>
      <html lang="en">
        <head>
          <link rel="stylesheet" type="text/css" href="/path/to/notifications.css" />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <NavigationWrapper />  {/* Render NavigationWrapper, which handles session check */}
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
